version: '3'

services:
  redis:
    image: redislabs/redisearch:latest
    container_name: redis
    volumes:
      - redis-data:/data
    networks:
      - opengpts

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-8100}:8100"
    depends_on:
      redis:
        condition: service_started
    environment:
      - "REDIS_URL=redis://redis:6379"
      - "OPENAI_API_KEY=${OPENAI_API_KEY:-placeholder}"
      - "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-placeholder}"
      - "YDC_API_KEY=${YDC_API_KEY:-placeholder}"
      - "KAY_API_KEY=${KAY_API_KEY:-placeholder}"
      - "TAVILY_API_KEY=${TAVILY_API_KEY:-placeholder}"
      - "LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY:-placeholder}"
      - "LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2:-false}"
      - "LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT:-placeholder}"
      - "AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY:-placeholder}"
      - "AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION:-placeholder}"
      - "AZURE_OPENAI_API_BASE=${AZURE_OPENAI_API_BASE:-placeholder}"
      - "AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME:-placeholder}"
      - "AZURE_OPENAI_MODEL_VERSION=${AZURE_OPENAI_MODEL_VERSION:-placeholder}"
    networks:
      - opengpts
    command: ["poetry", "run", "uvicorn", "app.server:app", "--host", "0.0.0.0", "--port", "8100"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      backend:
        condition: service_started
    networks:
      - opengpts
    command: ["yarn", "dev"]


volumes:
  redis-data:

networks:
  opengpts:
    driver: bridge
